### ISSUE TITLE
Add a note in the README on how to escape a URI with params

### ISSUE THREAD

**Issue by alexagranov** [jmervine/httperfrb#1]
Nice job on the wrapper!

One note - since this is using PTY.spawn under the hood, it might be nice to add a note on the README about how to hit a URI with multiple params - otherwise the '&' gets interpreted by the shell to background the job and perf.run just returns the empty string.

Something along the lines of:

`perf_with_params = HTTPerf.new( "server" => "host", "uri" => "'/foo?param1=bar&param2=baz'" )`

**Comment by jmervine** [comment]
@alexagranov Good call, I'll make the update shortly. Sorry for the  delayed response.

**Comment by jmervine** [comment]
Released with https://rubygems.org/gems/httperfrb/versions/0.3.13
